
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: nodejs-example
  namespace: default
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile

  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.1.0
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
