apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: default
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
  username: <username>
  password: <password>
